---
title: "hw3_ryw2109"
author: "Rita Wang"
date: "2024-10-16"
output: github_document
---

```{r default_setting, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(ggthemes)
library(ggridges)
library(patchwork)
# Importing data
  # devtools::install_github("p8105/p8105.datasets") --> installing dataset for P8105
library(p8105.datasets)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "hue",
  ggplot2.continuous.fill = "hue"
)
```

### Question 1
```{r Q3_dataset, echo = FALSE, message = FALSE, warning = FALSE}
data("ny_noaa") # calling for ny_noaa data
# ny_noaa #displays ny_noaa

nynoaa_df = ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
    # Create separate variables for year, month, and day
  mutate( # Ensure observations for temperature, precipitation, and snowfall are given in reasonable units
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin)
    )

nynoaa_df %>% 
  count(snow) %>%
  arrange(desc(n))

# nynoaa_df
```
Reasonable units for maximum and minimum temperature is Celsius, and reasonable units for precipitation, snowfall, and snowfall depth is mm. For snowfall, the most commonly observed value is 0 mm to which there were 2008508 observed data values; this is because snow does not commonly occur throughout the year.