p8105_hw3_ryw2109
================
Rita Wang
2024-10-16

### Question 1

``` r
data("ny_noaa") # calling for ny_noaa data
# ny_noaa #displays ny_noaa

nynoaa_df = ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
    # Create separate variables for year, month, and day
  mutate( # Ensure observations for temperature, precipitation, and snowfall are given in reasonable units
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin)
    )

nynoaa_df %>% 
  count(snow) %>%
  arrange(desc(n))
```

    ## # A tibble: 282 × 2
    ##     snow       n
    ##    <int>   <int>
    ##  1     0 2008508
    ##  2    NA  381221
    ##  3    25   31022
    ##  4    13   23095
    ##  5    51   18274
    ##  6    76   10173
    ##  7     8    9962
    ##  8     5    9748
    ##  9    38    9197
    ## 10     3    8790
    ## # ℹ 272 more rows

There is a total of 2595176 rows and 9 columns. The following are the
variable names of the dataset:

id, year, month, day, prcp, snow, snwd, tmax, tmin

Reasonable units for maximum and minimum temperature is Celsius, and
reasonable units for precipitation, snowfall, and snowfall depth is mm.
For snowfall, the most commonly observed value is 0 mm to which there
were 2008508 observed data values; this is because snow does not
commonly occur throughout the year.

``` r
# Make a two-panel plot showing the average max temperature in January and in July in each station across years
nynoaa_df %>% 
  group_by(
    id, year, month
    ) %>% 
  filter(
    month %in% c(1, 7) #January and in July
    ) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE) # average max temperature
    ) %>% 
  ggplot(aes(x = year, y = mean_tmax, group = id, color = month)) + 
  geom_point(aes(alpha = 0.3)) + 
  facet_grid(. ~ month) + #two-panel plot 
  labs(
    title = "Mean monthly temperature for each station across years for January and July",
    x = "Month",
    y = "Temperature (Celsius)"
  )
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

    ## Warning: Removed 5970 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

<img src="p8105_hw3_ryw2109_files/figure-gfm/Q1_B-1.png" width="90%" />

The average maximum temperature in January is much lower than that of
July. There is one outlier in July around 1985 to which the temperature
is slightly colder than the other average maximum temperature in July.

``` r
hex_nynoaa_df = nynoaa_df %>% 
  ggplot(aes (x = tmin , y = tmax) ) + # tmax vs tmin for the full dataset
  geom_hex()

ridges_nynoaa_df = nynoaa_df %>% 
  filter(snow < 100, snow > 0) %>% # snowfall values greater than 0 and less than 100
  ggplot(aes (x = snow , y = as.factor(year))) + # separately by year.
  geom_density_ridges() # distribution

hex_nynoaa_df + ridges_nynoaa_df #two-panel plot
```

    ## Warning: Removed 1136276 rows containing non-finite outside the scale range
    ## (`stat_binhex()`).

    ## Picking joint bandwidth of 3.76

<img src="p8105_hw3_ryw2109_files/figure-gfm/Q1_C-1.png" width="90%" />

### Question 2

``` r
demograph = read_csv(file = "./data/nhanes_covar.csv", skip = 4) %>%  #import data
    # rows 1-3 had legends
  janitor::clean_names()  #clean column name
```

    ## Rows: 250 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (5): SEQN, sex, age, BMI, education
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
demograph
```

    ## # A tibble: 250 × 5
    ##     seqn   sex   age   bmi education
    ##    <dbl> <dbl> <dbl> <dbl>     <dbl>
    ##  1 62161     1    22  23.3         2
    ##  2 62164     2    44  23.2         3
    ##  3 62169     1    21  20.1         2
    ##  4 62174     1    80  33.9         3
    ##  5 62177     1    51  20.1         2
    ##  6 62178     1    80  28.5         2
    ##  7 62180     1    35  27.9         3
    ##  8 62184     1    26  22.1         2
    ##  9 62186     2    17  22.9        NA
    ## 10 62189     2    30  22.4         3
    ## # ℹ 240 more rows

``` r
accelerometer = read_csv(file = "./data/nhanes_accel.csv") %>%  #import data
  janitor::clean_names()  #clean column name
```

    ## Rows: 250 Columns: 1441
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (1441): SEQN, min1, min2, min3, min4, min5, min6, min7, min8, min9, min1...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
accelerometer
```

    ## # A tibble: 250 × 1,441
    ##     seqn  min1  min2  min3  min4   min5   min6  min7   min8    min9  min10
    ##    <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>   <dbl>  <dbl>
    ##  1 62161 1.11  3.12  1.47  0.938 1.60   0.145  2.10  0.509   1.63   1.20  
    ##  2 62164 1.92  1.67  2.38  0.935 2.59   5.22   2.39  4.90    1.97   3.13  
    ##  3 62169 5.85  5.18  4.76  6.48  6.85   7.24   6.12  7.48    5.47   6.49  
    ##  4 62174 5.42  3.48  3.72  3.81  6.85   4.45   0.561 1.61    0.698  2.72  
    ##  5 62177 6.14  8.06  9.99  6.60  4.57   2.78   7.10  7.25   10.1    7.49  
    ##  6 62178 0.167 0.429 0.131 1.20  0.0796 0.0487 0.106 0.0653  0.0564 0.0639
    ##  7 62180 0.039 0     0     0     0.369  0.265  0.506 0.638   0      0.011 
    ##  8 62184 1.55  2.81  3.86  4.76  6.10   7.61   4.74  6.73    5.42   4.24  
    ##  9 62186 3.08  2.54  2.63  2.12  1.14   1.68   2.84  2.72    2.13   2.18  
    ## 10 62189 2.81  0.195 0.163 0     0.144  0.180  0.870 0.214   0      0     
    ## # ℹ 240 more rows
    ## # ℹ 1,430 more variables: min11 <dbl>, min12 <dbl>, min13 <dbl>, min14 <dbl>,
    ## #   min15 <dbl>, min16 <dbl>, min17 <dbl>, min18 <dbl>, min19 <dbl>,
    ## #   min20 <dbl>, min21 <dbl>, min22 <dbl>, min23 <dbl>, min24 <dbl>,
    ## #   min25 <dbl>, min26 <dbl>, min27 <dbl>, min28 <dbl>, min29 <dbl>,
    ## #   min30 <dbl>, min31 <dbl>, min32 <dbl>, min33 <dbl>, min34 <dbl>,
    ## #   min35 <dbl>, min36 <dbl>, min37 <dbl>, min38 <dbl>, min39 <dbl>, …

``` r
demo_accel = left_join(demograph , accelerometer , by = "seqn") %>% 
    mutate ( # encode data with reasonable variable classes
    seqn = as.integer(seqn),
    sex = as.integer(sex),
    age = as.integer(age),
    education = as.integer(education)
  ) %>%
  filter(age >= 21) %>% # excluding participants less than 21 years of age
  drop_na("sex", "age", "bmi") # excluding those with missing demographic data

demo_accel
```

    ## # A tibble: 228 × 1,445
    ##     seqn   sex   age   bmi education  min1   min2   min3  min4   min5   min6
    ##    <int> <int> <int> <dbl>     <int> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl>
    ##  1 62161     1    22  23.3         2 1.11  3.12   1.47   0.938 1.60   0.145 
    ##  2 62164     2    44  23.2         3 1.92  1.67   2.38   0.935 2.59   5.22  
    ##  3 62169     1    21  20.1         2 5.85  5.18   4.76   6.48  6.85   7.24  
    ##  4 62174     1    80  33.9         3 5.42  3.48   3.72   3.81  6.85   4.45  
    ##  5 62177     1    51  20.1         2 6.14  8.06   9.99   6.60  4.57   2.78  
    ##  6 62178     1    80  28.5         2 0.167 0.429  0.131  1.20  0.0796 0.0487
    ##  7 62180     1    35  27.9         3 0.039 0      0      0     0.369  0.265 
    ##  8 62184     1    26  22.1         2 1.55  2.81   3.86   4.76  6.10   7.61  
    ##  9 62189     2    30  22.4         3 2.81  0.195  0.163  0     0.144  0.180 
    ## 10 62199     1    57  28           3 0.031 0.0359 0.0387 0.079 0.109  0.262 
    ## # ℹ 218 more rows
    ## # ℹ 1,434 more variables: min7 <dbl>, min8 <dbl>, min9 <dbl>, min10 <dbl>,
    ## #   min11 <dbl>, min12 <dbl>, min13 <dbl>, min14 <dbl>, min15 <dbl>,
    ## #   min16 <dbl>, min17 <dbl>, min18 <dbl>, min19 <dbl>, min20 <dbl>,
    ## #   min21 <dbl>, min22 <dbl>, min23 <dbl>, min24 <dbl>, min25 <dbl>,
    ## #   min26 <dbl>, min27 <dbl>, min28 <dbl>, min29 <dbl>, min30 <dbl>,
    ## #   min31 <dbl>, min32 <dbl>, min33 <dbl>, min34 <dbl>, min35 <dbl>, …

After merging the two datasets, there is now a total of 228 rows and
1445 columns.

It can be seen that the original data set had seqn, sex, age, and
education recorded as dbls, however, they are integers.

``` r
# table for the number of men and women in each education category
demo_accel %>% 
  group_by(sex, education) %>% 
  summarize(total_count = n()) %>% 
  pivot_wider(
    names_from = "education",
    values_from = total_count
  ) %>% 
  knitr::kable(digits = 1)
```

    ## `summarise()` has grouped output by 'sex'. You can override using the `.groups`
    ## argument.

| sex |   1 |   2 |   3 |
|----:|----:|----:|----:|
|   1 |  27 |  35 |  56 |
|   2 |  28 |  23 |  59 |

``` r
# age distributions for men and women in each education category
demo_accel %>%
  ggplot(aes(x = age, fill = as.factor(sex))) +
  geom_histogram(position = "dodge") +
  facet_grid(. ~ education) +
  labs(title = "Age Distribution For Sex VS Education",
       x = "Age",
       y = "Count"
  )
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

<img src="p8105_hw3_ryw2109_files/figure-gfm/Q2_B-1.png" width="90%" />

Based on the histogram, among those with an education less than high
school, it can be seen there is a larger number of females and males who
are of an older age (60 and above). Based on the table created, there
are 27 males and 28 females who have an education less than high school.

Based on the histogram, among those with an education equivalent to high
school, it can be seen there is a relatively even spread across the
different ages. Based on the table created, there are 35 males and 23
females who have an education if high school equivalent.

Based on the histogram, among those with an education more than high
school, it can be seen there is a larger number of females and males who
are of a younger age (40 and below). Based on the table created, there
are 56 males and 59 females who have an education more than high school.

Across the three histograms, it can be seen that there are more
individuals who have an education more than high school.

``` r
total_demo_accel = demo_accel %>%
  mutate(
    total_activities = rowSums(select(., starts_with("min"))) # sums all the values of min1:min1440 for each participant
  ) %>% 
  select(
    seqn, sex, age, bmi, education, total_activities
    ) 

total_demo_accel %>% 
  ggplot(aes(x = age, y = total_activities, color = sex)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ education) +
  labs(title = "Total Activity By Age For Sex VS Education",
       x = "Age",
       y = "Total Activity"
  )
```

    ## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'

    ## Warning: The following aesthetics were dropped during statistical transformation:
    ## colour.
    ## ℹ This can happen when ggplot fails to infer the correct grouping structure in
    ##   the data.
    ## ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
    ##   variable into a factor?
    ## The following aesthetics were dropped during statistical transformation:
    ## colour.
    ## ℹ This can happen when ggplot fails to infer the correct grouping structure in
    ##   the data.
    ## ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
    ##   variable into a factor?
    ## The following aesthetics were dropped during statistical transformation:
    ## colour.
    ## ℹ This can happen when ggplot fails to infer the correct grouping structure in
    ##   the data.
    ## ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
    ##   variable into a factor?

<img src="p8105_hw3_ryw2109_files/figure-gfm/Q2_C-1.png" width="90%" />

From the graphs, we can see that for all 3 educational levels, there is
a general decrease of activity as age increases.

For individuals with an education less than high school, older males had
higher total activity compared to females. Between age 50 to 60, the
originally decreasing total activity with age had an increase.

For individuals with an education equivalent to high school, younger and
older females had higher total activity compared to males. Between age
30 to 40, there seems to be an increase of total activity. At age 40,
the total activity decreased and leveled off starting at age 55.

For individuals with an education higher than high school, older females
had higher total activity compared to males. In general, there is a
general decrease in total activity as age increases.

``` r
long_hour_demo_accel = demo_accel %>%
  select(seqn, sex, age, bmi, education, min1:min1440) %>% 
  mutate( # converting minutes to hours
    hour1 = rowSums(select(., min1:min60)),
    hour2 = rowSums(select(., min61:min120)),
    hour3 = rowSums(select(., min121:min180)),
    hour4 = rowSums(select(., min181:min240)),
    hour5 = rowSums(select(., min241:min300)),
    hour6 = rowSums(select(., min301:min360)),
    hour7 = rowSums(select(., min361:min420)),
    hour8 = rowSums(select(., min421:min480)),
    hour9 = rowSums(select(., min481:min540)),
    hour10 = rowSums(select(., min541:min600)),
    hour11 = rowSums(select(., min601:min660)),
    hour12 = rowSums(select(., min661:min720)),
    hour13 = rowSums(select(., min721:min780)),
    hour14 = rowSums(select(., min781:min840)),
    hour15 = rowSums(select(., min841:min900)),
    hour16 = rowSums(select(., min901:min960)),
    hour17 = rowSums(select(., min961:min1020)),
    hour18 = rowSums(select(., min1021:min1080)),
    hour19 = rowSums(select(., min1081:min1140)),
    hour20 = rowSums(select(., min1141:min1200)),
    hour21 = rowSums(select(., min1201:min1260)),
    hour22 = rowSums(select(., min1261:min1320)),
    hour23 = rowSums(select(., min1321:min1380)),
    hour24 = rowSums(select(., min1381:min1440))
  )

hour_demo_accel = long_hour_demo_accel %>% 
  select(seqn, sex, age, bmi, education, hour1:hour24) %>% 
  pivot_longer( # converts the hour1:hour24 columns into rows
    hour1:hour24,
    names_to = "hr",
    names_prefix = "",
    values_to = "hour_activity"
    ) %>% 
  mutate(
    hr = gsub("hour", "", hr),
    hr = as.integer(hr)
  )

hour_demo_accel %>% 
  ggplot(aes(x = hr, y = hour_activity, color = sex)) +
  geom_point(aes(alpha = 0.5)) +
  facet_grid(. ~ education) +
  labs(title = "Hourly Activity For Sex VS Education",
       x = "Hours",
       y = "Activity"
  )
```

<img src="p8105_hw3_ryw2109_files/figure-gfm/Q2_D-1.png" width="90%" />

The average activity of a 24 hour time period have a relatively similar
spread of across all 3 education levels, with a low amount of activity
within in the first 5 hours of a day to which the total activity
increases peaking at hour 10-15. Males and females with an education
less than high school have a relatively similar spread of exercise. For
those with an education equivalent to high school, we see that the data
points are darker for each hour, indicating that more males are having
activities than females for a given time period. For those with an
education higher than high school, we see that the data points are
lighter for each hour, indicating that more females are having
activities than males for a given time period.

### Question 3

``` r
janurary_20 = read_csv(file = "./data/Jan 2020 Citi.csv") %>%  #import data
  janitor::clean_names() %>% #clean column name
  mutate(
    time_period = "2020-01",
    month = 1,
    year = 2020
  )
```

    ## Rows: 12420 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
janurary_24 = read_csv(file = "./data/Jan 2024 Citi.csv") %>%  #import data
  janitor::clean_names() %>% #clean column name
  mutate(
    time_period = "2024-01",
    month = 1,
    year = 2024
  )
```

    ## Rows: 18861 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
july_20 = read_csv(file = "./data/July 2020 Citi.csv") %>%  #import data
  janitor::clean_names()  %>% #clean column name
  mutate(
    time_period = "2020-07",
    month = 7,
    year = 2020
  )
```

    ## Rows: 21048 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
july_24 = read_csv(file = "./data/July 2024 Citi.csv") %>%  #import data
  janitor::clean_names()  %>% #clean column name
  mutate(
    time_period = "2024-07",
    month = 7,
    year = 2024
  )
```

    ## Rows: 47156 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
citi = bind_rows(janurary_20, july_20, janurary_24, july_24)

citi %>% # type of rideable_type data in the data set
  count(rideable_type) %>%
  arrange(desc(n))
```

    ## # A tibble: 2 × 2
    ##   rideable_type     n
    ##   <chr>         <int>
    ## 1 classic_bike  55536
    ## 2 electric_bike 43949

``` r
citi %>% # type of duration data in the data set --> trying to determine if time is in hr or min
  count(duration) %>%
  arrange(desc(duration))
```

    ## # A tibble: 97,274 × 2
    ##    duration     n
    ##       <dbl> <int>
    ##  1     239.     1
    ##  2     236.     1
    ##  3     232.     1
    ##  4     232.     1
    ##  5     231.     1
    ##  6     231.     1
    ##  7     230.     1
    ##  8     230.     1
    ##  9     229.     1
    ## 10     227.     1
    ## # ℹ 97,264 more rows

``` r
citi %>% # type of member_casual data in the data set
  count(member_casual) %>%
  arrange(desc(n))
```

    ## # A tibble: 2 × 2
    ##   member_casual     n
    ##   <chr>         <int>
    ## 1 member        79862
    ## 2 casual        19623

In 01/2020, there were a total of 12420 records recorded. In 01/2024,
there were a total of 18861 records recorded. In 07/2020, there were a
total of 21048 records recorded. In 07/2024, there were a total of 47156
records recorded.

All four datasets have 10. The dataset describes the type of ride an
individual uses (classic or electric bike), which date of the week the
ride was used, the total duration the ride was in minutes as there were
values greater than 4, start and end station location, whether or not an
individual was a casual or member rider.

``` r
# table showing the total number of rides in each combination of year and month separating casual riders and Citi Bike members
citi %>% 
  group_by(time_period, member_casual) %>% 
  summarize(total_count = n()) %>% 
  pivot_wider(
    names_from = "member_casual",
    values_from = total_count
  ) %>% 
  knitr::kable(digits = 1)
```

    ## `summarise()` has grouped output by 'time_period'. You can override using the
    ## `.groups` argument.

| time_period | casual | member |
|:------------|-------:|-------:|
| 2020-01     |    984 |  11436 |
| 2020-07     |   5637 |  15411 |
| 2024-01     |   2108 |  16753 |
| 2024-07     |  10894 |  36262 |

From the table above, it can be seen that as time progresses, both the
number of casual riders and Citi Bike members increased. From 01/2020 to
07/2024, the number of casual riders have increased more than 10 folds
and the number of Citi Bike members have increased more than 2 folds.

``` r
# table showing the 5 most popular starting stations for July 2024
july_24 %>% 
  group_by(start_station_name) %>% 
  summarize(total_count = n()) %>% 
  arrange(desc(total_count)) %>% 
  slice_head(n = 5) %>% # because the stations are on the columns, head() couldnt be used
  pivot_wider(
    names_from = "start_station_name",
    values_from = total_count
  )
```

    ## # A tibble: 1 × 5
    ##   `Pier 61 at Chelsea Piers` `University Pl & E 14 St` `W 21 St & 6 Ave`
    ##                        <int>                     <int>             <int>
    ## 1                        163                       155               152
    ## # ℹ 2 more variables: `West St & Chambers St` <int>, `W 31 St & 7 Ave` <int>

The top 5 most population starting stations in 07/2024, was the
following:

Pier 61 at Chelsea Piers University Pl & E 14 St W 21 St & 6 Ave West St
& Chambers St W 31 St & 7 Ave

The 5 stations has a range of 146-163 riders in 07/2024.

``` r
# effects of day of the week, month, and year on median ride duration
citi %>% 
  mutate(
    weekdays = recode(weekdays,
      "Monday" = "1",
      "Tuesday" = "2",
      "Wednesday" = "3",
      "Thursday" = "4",
      "Friday" = "5",
      "Saturday" = "6",
      "Sunday" = "7"
      )
  ) %>% 
  group_by(weekdays, month, year) %>% 
  summarize(median_count = median(duration)) %>% 
  ggplot(aes(x = as.factor(weekdays), y = median_count, color = month)) +
  geom_point() + 
  facet_grid(. ~ as.factor(year)) +
  scale_x_discrete(labels = c("1" = "Monday", "2" = "Tuesday", "3" = "Wednesday", 
                               "4" = "Thursday", "5" = "Friday", "6" = "Saturday", 
                               "7" = "Sunday")) +
  labs(title = "Median Ride Duration By Day of Week",
       x = "Day of Week",
       y = "Median Ride Duration"
  )
```

    ## `summarise()` has grouped output by 'weekdays', 'month'. You can override using
    ## the `.groups` argument.

<img src="p8105_hw3_ryw2109_files/figure-gfm/Q3_D-1.png" width="90%" />

There are more riders in July compared to January for both 2020 and
2024, and across all days of the week

``` r
citi_2024 = bind_rows(janurary_24, july_24)

citi_2024 %>%
  group_by(month, member_casual, rideable_type) %>% 
  ggplot(aes(x = duration, fill = interaction(member_casual, rideable_type))) +
  geom_histogram(position = "dodge") +
  facet_grid(. ~ month) +
  labs(title = "Rides Duration in Janurary_24 and July 2024",
       x = "Month",
       y = "Ride Duration"
  )
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

<img src="p8105_hw3_ryw2109_files/figure-gfm/Q3_E-1.png" width="90%" />

There is a higher duration of rides in July compared to January, which
can be seen by comparing the two graphs. Both months seems to have a
similar trend, where there are more electric bike riders than classic
bike riders, as well as more members than casual individuals, especially
in July. In both months, the peak of ride duration was around 15 miles,
with relatively few individuals having a ride duration of over 50 miles.
